os:
  - linux
  - osx

env:
  global:
    - KERL_BASE_DIR="$TMPDIR"/.kerl
    - KERL_CONFIGURE_DISABLE_APPLICATIONS="odbc"
  matrix: 
    - _KERL_VSN=19.2 
    - _KERL_VSN=18.3
    - _KERL_VSN=17.5
    - _KERL_VSN=R16B03-1
    - _KERL_VSN=R15B03-1

script:
  - ./kerl update releases
  - travis_wait 30 ./kerl build "$_KERL_VSN" "$_KERL_VSN"
  - ./kerl install "$_KERL_VSN" "install_$_KERL_VSN"
  - ./kerl status
  - source $(./kerl path install_$_KERL_VSN)/activate
  - erl -s crypto -s init stop
  - kerl_deactivate
  - ./kerl delete installation $(./kerl path install_$_KERL_VSN)
  - ./kerl delete build "$_KERL_VSN"
