language: bash
sudo: false
os: osx

env:
  global:
  - KERL_BASE_DIR="$TMPDIR"/.kerl
  - KERL_BUILD_BACKEND=git
  - KERL_CONFIGURE_DISABLE_APPLICATIONS='odbc'
  matrix:
  - _KERL_VSN=21.0
  - _KERL_VSN=20.3
  - _KERL_VSN=19.3
  - _KERL_VSN=18.3
  - _KERL_VSN=17.5
  - _KERL_VSN=R16B03-1

install:
# https://github.com/kerl/kerl/issues/226#issuecomment-327915702
# https://github.com/Homebrew/homebrew-core/issues/47348
- |
  if [[ "_KERL_VSN" = 2* ]]; then
    brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/64555220bfbf4a25598523c2e4d3a232560eaad7/Formula/openssl.rb -f
    brew --prefix openssl || true
    brew link openssl || true
    brew --prefix openssl || true
    export KERL_CONFIGURE_OPTIONS=--with-ssl="$(brew --prefix openssl)"
  fi
script:
- ./kerl update releases
- travis_wait 45 ./kerl build "$_KERL_VSN" "$_KERL_VSN"
- ./kerl install "$_KERL_VSN" "install_$_KERL_VSN"
- ./kerl status
- |
  source $(./kerl path install_$_KERL_VSN)/activate
  erl -s crypto -s init stop
  erl_call
  kerl_deactivate
- |
  otp_major=$(echo "$_KERL_VSN" | cut -d. -f1)
  if ((travis_otp_major >= 18)); then
    source $(./kerl path install_$_KERL_VSN)/activate
    ./kerl install-docsh
    kerl_deactivate
    source $(./kerl path install_$_KERL_VSN)/activate
    erl -noshell -eval 'h(proplists).' -s init stop
    kerl_deactivate
  fi
- ./kerl delete installation $(./kerl path install_$_KERL_VSN)
- ./kerl delete build "$_KERL_VSN"
