version: 2
workflows:
  version: 2
  test-workflow:
    jobs:
      - alpine_master

jobs:

  alpine_master:
    docker: [{image: 'alpine'}]
    environment:
    - _KERL_VSN: master
    - KERL_BUILD_DOCS: 'yes'
    steps:
    - run: apk update && apk upgrade
    - run: |
        apk add curl ca-certificates \
                dpkg-dev dpkg \
                gcc g++ libc-dev linux-headers make autoconf ncurses-dev tar \
                openssl-dev lksctp-tools-dev lksctp-tools \
                libxslt git
    - checkout
    - run:
        no_output_timeout: 45m
        command:
          |
            export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
            ./kerl build git https://github.com/erlang/otp.git "$_KERL_VSN" "$_KERL_VSN"
    - run: &kerl_install ./kerl install "$_KERL_VSN" "install_$_KERL_VSN"
    - run: &kerl_status  ./kerl status
    - run: &activate_then_test_for_crypto
        |
          source $(./kerl path install_"$_KERL_VSN")/activate
          erl -s crypto -s init stop
          erl_call
          kerl_deactivate
    - run: &kerl_delete_installation
        |
          ./kerl delete installation $(./kerl path install_"$_KERL_VSN")
    - run: &kerl_delete_build ./kerl delete build "$_KERL_VSN"
