version: 2
jobs:

  build:
    docker:
      - image: debian:8
    environment:
      - _KERL_VSN: R15B03-1
      - KERL_CONFIGURE_DISABLE_APPLICATIONS: 'odbc'
    steps:
      - run: apt-get update && apt-get upgrade -y
      - run: apt-get install -y git curl build-essential libncurses-dev libssl-dev
      - checkout
      - run: ./kerl update releases
      - run:
          command: ./kerl build "$_KERL_VSN" "$_KERL_VSN"
          no_output_timeout: 45m
      - run: ./kerl install "$_KERL_VSN" "install_$_KERL_VSN"
      - run: ./kerl status
      - run: |
          set -x
          source $(./kerl path install_$_KERL_VSN)/activate
          erl -s crypto -s init stop
          kerl_deactivate
      - run: ./kerl delete installation $(./kerl path install_$_KERL_VSN)
      - run: ./kerl delete build "$_KERL_VSN"

  centos6_20.2:
    docker:
      - image: centos:6
    environment:
      - _KERL_VSN: 20.2
      - KERL_CONFIGURE_DISABLE_APPLICATIONS: 'odbc'
    steps:
      - run: yum -y update
      - run: yum -y install curl ncurses-devel openssl-devel make automake autoconf gcc gcc-c++ gcc-java
      - run: |
          yum -y install https://centos6.iuscommunity.org/ius-release.rpm
          # CircleCI checkout uses -B which isn't available in CentOS6's packaged git
          yum -y install git2u
      - checkout
      - run: ./kerl update releases
      - run:
          command: ./kerl build "$_KERL_VSN" "$_KERL_VSN"
          no_output_timeout: 45m
      - run: ./kerl install "$_KERL_VSN" "install_$_KERL_VSN"
      - run: ./kerl status
      - run: |
          set -x
          source $(./kerl path install_$_KERL_VSN)/activate
          erl -s crypto -s init stop
          kerl_deactivate
      - run: ./kerl delete installation $(./kerl path install_$_KERL_VSN)
      - run: ./kerl delete build "$_KERL_VSN"

workflows:
  version: 2
  test-workflow:
    jobs:
      - build
      - centos6_20.2
